# This is a workflow to get the scraping data from the websites

name: getScrapingData

# Controls when the workflow will run
on:
  schedule:
  - cron: "11 9 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
              node-version: 16

      # Runs a single command using the runners shell
      - name: Install puppeteer
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Run the scraper script
        run: npm run getData
